### ISSUE TITLE
Ideas and features

### ISSUE THREAD

**Issue by Glajik** [Glajik/diet-routine#1]
Предлагаю набросать в этой ветке идеи - какие возможности вы хотите видеть в приложении "Дневник питания".

Можете добавить скрины подобных приложений (мобильных или веб), а так же интерфейсы других программ которые вам нравятся - welome.

**Note** *Чтобы добавить картинку - загрузите картинку на imgur и используйте markdown синтаксис `![alt-text](url)`.*

[More about markdown](https://guides.github.com/features/mastering-markdown/)

Вот уже несколько идей:
1. Мастер после регистрации для установки целей, расчета нормы в зависимости от пола, возраста, веса, цели и желаемой скорости.
1. Обзор возможностей программы с обучением.
1. Учет не только калорий, но и белков жиров и углеводов. Установка нужного соотношения.
1. Отслеживание изменений веса
1. Конструктор составных продуктов, например "Кофе с молоком", "Летний салат"
1. Ввод количества порций. При этом дать возможность индивидуально настроить, какой вес продукта будет на одну порцию.
1. Отмечать количество выпитой воды тапом по стаканчикам
1. Разные источники данных и фильтр при поиске
    - Общая база со стандартными продуктами
    - Общая база всех пользователей
    - Личная база
    - Открытая база продуктов через API
    - Google (парсить вывод)
1. Советы по приемам пищи
1. Предложения часто используемых продуктов. При этом учитывать завтрак это, обед или ужин. Например не предлагать кофе вечером.
1. Ввод продукта при помощи скана штрихкода на этикетке
1. Режим специальной лечебной диеты
    - Описание диеты (из википедии)
    - Предлагать продукты которые позволено диетой
    - Подбор по цене или категории
1. Планирование закупок и предложения по закупкам (отслеживать потребление и делать заключение что например заканчиваются овощи)
1. Телеграм чат бот, чтобы можно было быстро ввести и с телефона. Или сделать себе напоминание, чтобы заполнить потом (может фото?)
1. Если будет достаточно времени - сделать ReactNative приложение, пусть и с урезанным функционалом

**Comment by AndriiStolitnii** [comment]
Предложения: 
1) Физическая активность - возможность добавить в свой дневник питания занятие спортом (фитнес, тренажерный зал, бег, вело, плавание, ролики, ходьба ...). Физическая активность повышает потребность в калориях, чтобы восполнить затраты организма.
2) Система достижений в приложении - 7 дней подряд придерживался цели, 30 дней, достиг цели по весу и т.д. 
3) Возможность поделиться в соцсетях своим достижением. Также, возможно стоит добавить фичу "поделиться в соцсетях" для поставленных целей, потому что публично взятые обязательства больше мотивируют
4) Если мы будем давать советы по питанию (условно, "вы потребляете много сахара, это вредно") - было бы хорошо сделать кнопку-ссылку, которая позволит почитать более подробную информацию о вреде сахара, быстрых углеводов, недостаточного количества воды, белков или жиров, пользы больщего кол-ва приемов пищи из источников, пользующихся неоспоримым доверием

[Lifesum](https://lifesum.com/ru/features/) - сайт приложения lifesum, которым я пользовался (оттуда идея с тапом по стаканам). По ссылке внешний вид и описание их фич
