### ISSUE TITLE
App sketch

### ISSUE THREAD

**Issue by Glajik** [Glajik/diet-routine#11]
[Эскиз приложения в Figma](https://www.figma.com/file/PoVMjMwDbY43kq66JzMfV2/app-sketch?node-id=169%3A189)

**Comment by AndriiStolitnii** [comment]
![P00903-180555](https://user-images.githubusercontent.com/45840046/92143481-05aee900-ee1e-11ea-992f-ace07b96b9ad.jpg)
![P00903-180617](https://user-images.githubusercontent.com/45840046/92143489-08114300-ee1e-11ea-828e-e101dcbece4a.jpg)
![P00903-180609](https://user-images.githubusercontent.com/45840046/92143492-09427000-ee1e-11ea-9ee3-f9cf5e2f13d5.jpg)
![P00903-180602](https://user-images.githubusercontent.com/45840046/92143495-0ba4ca00-ee1e-11ea-9119-a6ae0278d952.jpg)
Стартовая страница

**Comment by AndriiStolitnii** [comment]
![P00904-190133](https://user-images.githubusercontent.com/45840046/92260865-3ad03f80-eee1-11ea-8788-6be7286e08a3.jpg)
![P00904-190203](https://user-images.githubusercontent.com/45840046/92260873-3c9a0300-eee1-11ea-8ac7-d8f26b3e62e9.jpg)
![P00904-190122](https://user-images.githubusercontent.com/45840046/92260875-3dcb3000-eee1-11ea-8e01-a7d6817b99bb.jpg)
![P00904-190156](https://user-images.githubusercontent.com/45840046/92260879-3efc5d00-eee1-11ea-815b-83c38b9c6bd1.jpg)
![P00904-190149](https://user-images.githubusercontent.com/45840046/92260883-402d8a00-eee1-11ea-80f2-28a0623ebcdf.jpg)
![P00904-190140](https://user-images.githubusercontent.com/45840046/92260889-41f74d80-eee1-11ea-9581-4f7289afe800.jpg)

**Comment by AndriiStolitnii** [comment]
![P00907-180407](https://user-images.githubusercontent.com/45840046/92400488-aeb65600-f134-11ea-9357-7cd286563d25.jpg)
![P00907-180352](https://user-images.githubusercontent.com/45840046/92400496-b1b14680-f134-11ea-8d81-84a610cfa215.jpg)
![P00907-180359](https://user-images.githubusercontent.com/45840046/92400503-b413a080-f134-11ea-938e-1a3c824a2cb6.jpg)
![P00907-180329](https://user-images.githubusercontent.com/45840046/92400510-b70e9100-f134-11ea-9109-c7af4b1353b9.jpg)
![P00907-180343](https://user-images.githubusercontent.com/45840046/92400521-bbd34500-f134-11ea-9519-67b0439a34a2.jpg)
![P00907-180337](https://user-images.githubusercontent.com/45840046/92400528-bece3580-f134-11ea-9746-f271572516a7.jpg)
