### ISSUE TITLE
Bootstrap and custom design

### ISSUE THREAD

**Issue by Glajik** [Glajik/diet-routine#5]
- Погуглить как на самом деле можно стилизовать Bootstrap. Возможно есть правильный способ это делать, о котором мы пока не знаем.
- Написать в коментах мнение, и ссылки.

**Comment by Vadim121197** [comment]
я начал вникать в дизайн-системы, и наткнулся на то что можно сделать каскад сайта без использования Bootstrap В построении каскада нам может помочь **CSS grid layout**! и так мы не будем зависить от уже предложенных нам вариантов, а сможем сделать что-то своё!

**Comment by Vadim121197** [comment]
[как можно красиво сделать с GRID](https://www.youtube.com/watch?v=M1Wr2GA_z5c)

**Comment by Glajik** [comment]
> я начал вникать в дизайн-системы, и наткнулся на то что можно сделать каскад сайта без использования Bootstrap В построении каскада нам может помочь **CSS grid layout**! и так мы не будем зависить от уже предложенных нам вариантов, а сможем сделать что-то своё!

Подписан на этого парня, нравится его обучающие ролики. Советую глянуть по теме:
[Адаптивная верстка - тебе не нужен Bootstrap!](https://www.youtube.com/watch?v=XbnAKjjlgc4)

Однако еще раз скажу, что взгляд на Bootstrap как на сетку и набор компонентов слишком примитивен. Хочу чтобы у вас сложилось понимание какие задачи решают дизайн системы.

**Comment by valyuscha** [comment]
> я начал вникать в дизайн-системы, и наткнулся на то что можно сделать каскад сайта без использования Bootstrap В построении каскада нам может помочь **CSS grid layout**! и так мы не будем зависить от уже предложенных нам вариантов, а сможем сделать что-то своё!

Также существуют flex-box. Они ещё проще, чем grid. Благодаря им можно очень просто выстраивать сетку. И с адаптивом нет проблем

**Comment by Vadim121197** [comment]
Так если flexbox, то тогда можно использовать Bootstrap 4, он сделан на основе flexbox!

**Comment by Glajik** [comment]
Хочу потом составить список со ссылками
https://geekflare.com/best-css-frameworks/
